'use strict';

// Real-repo teardown: shallow-clone a curated set of well-known packages, scan
// each with slopscore, and print a Markdown Slop-Score table. This is a REPORTING
// tool (network + non-deterministic — repos change), not a CI test.
//
//   npm run teardown                       # scan the default curated set
//   node scripts/scan-repos.js <giturl>…   # scan specific repos
//
// The honest story it tells: established, well-maintained libraries score LOW —
// which is the calibration check that matters (the tool doesn't cry wolf on good code).

const { execFileSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { scan } = require('../src/scanner');
const { score } = require('../src/score');

const DEFAULT_REPOS = [
  'https://github.com/sindresorhus/slugify.git',
  'https://github.com/chalk/chalk.git',
  'https://github.com/expressjs/express.git',
  'https://github.com/axios/axios.git',
  'https://github.com/lodash/lodash.git',
];

function repoName(url) {
  return url.replace(/\.git$/, '').split('/').slice(-2).join('/');
}

function scanRepo(url) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'slopscore-teardown-'));
  const dest = path.join(dir, 'repo');
  try {
    execFileSync('git', ['clone', '--depth', '1', '--single-branch', '--quiet', url, dest], { stdio: 'ignore' });
  } catch {
    fs.rmSync(dir, { recursive: true, force: true });
    return { name: repoName(url), error: 'clone failed' };
  }
  try {
    const result = scan([dest], { ignoreBase: dest });
    const s = score(result);
    // The strong signal only — the precise detectors slopscore itself recommends
    // gating CI on (--min-confidence high): secrets, injection, empty catch, etc.
    // Excludes soft heuristics (var, ==, design/copy tells) that fire on legacy code.
    const highResult = { ...result, findings: result.findings.filter((f) => (f.confidence || 'high') === 'high') };
    const sh = score(highResult);
    const top = s.topRules && s.topRules[0] ? `${s.topRules[0][0]}×${s.topRules[0][1]}` : '—';
    return {
      name: repoName(url), kloc: s.kloc, weighted: s.weighted, density: s.density,
      densityHigh: sh.density, verdictHigh: sh.verdict,
      critical: s.counts.critical, major: s.counts.major, minor: s.counts.minor,
      verdict: s.verdict, top, files: result.fileCount,
    };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function main() {
  const urls = process.argv.slice(2).filter((a) => /^https?:\/\//.test(a));
  const repos = urls.length ? urls : DEFAULT_REPOS;
  process.stderr.write(`Scanning ${repos.length} repositories (shallow clone)…\n`);
  const rows = [];
  for (const url of repos) {
    process.stderr.write(`  · ${repoName(url)}\n`);
    rows.push(scanRepo(url));
  }
  const ok = rows.filter((r) => !r.error).sort((a, b) => a.densityHigh - b.densityHigh);
  const failed = rows.filter((r) => r.error);

  const out = [];
  out.push('# slopscore — real-repo teardown');
  out.push('');
  out.push(`Scanned ${ok.length} well-known packages with \`slopscore\` (shallow clone, production code only).`);
  out.push('Sorted by **high-confidence** Slop density (weighted findings/kLOC from the precise detectors —');
  out.push('secrets, injection, empty catch, etc. — the signal slopscore recommends gating CI on). The "all"');
  out.push('column adds the softer heuristics (`var`, `==`, design/copy tells) that fire on legacy code.');
  out.push('');
  out.push('| Repository | kLOC | 🔴 | 🟠 | 🟡 | Density (high-conf) | Verdict (high-conf) | Density (all) |');
  out.push('|:--|--:|--:|--:|--:|--:|:--|--:|');
  for (const r of ok) {
    out.push(`| ${r.name} | ${r.kloc} | ${r.critical} | ${r.major} | ${r.minor} | ${r.densityHigh} | ${r.verdictHigh} | ${r.density} |`);
  }
  out.push('');
  if (failed.length) out.push(`_Skipped (clone failed): ${failed.map((r) => r.name).join(', ')}_`);
  out.push('');
  out.push('_Generated by `npm run teardown`. slopscore is a fast regex/heuristic first pass — a low score means few AI-slop tells, not a proof of correctness._');
  process.stdout.write(out.join('\n') + '\n');
}

if (require.main === module) main();
module.exports = { scanRepo };
